### PR TITLE
NEMO-4796: Prefix 'COPY OF' not localized for cloned product

### PR DESCRIPTION
**Pull request by medius**

### CODE REVIEW

**Comment by IrvinFan** [comment]
Reviewing

**Comment by IrvinFan** [comment]
This line also needs to be localized: https://github.com/godaddy/spree/blob/nemo_4796/core/lib/spree/core/product_duplicator.rb#L53

**Comment by medius** [comment]
Made the change and added a test

**Comment by IrvinFan** [comment]
Code looks fine. Working as expect. Merging

**Pull request merged**
