### PR TITLE
NEMO-2967: As a merchant, I want to add multiple options for a product that are not tied to inventory so that my customers can select all the options they want to build a customized product.

### PR DESCRIPTION
**Pull request by medius**
Another one bites the dust (for options).

Related PR: https://github.secureserver.net/PC/nemo_spree/pull/467

### CODE REVIEW

**Comment by alanpaklo** [comment]
Code looks good. Spec passed. Good to merge.

**Comment by gchernoff** [comment]
Do we intend to contribute these changes back to Spree?   If not then I think we need some comments regarding why we are diverting from Spree.

**Comment by medius** [comment]
We should contribute it back to Spree. This is mostly a refactor that's useful in overriding spree components.

What process do we follow to contribute back to Spree, especially when we are using an older version?

**Comment by mjaniszewski** [comment]
Merging.

**Pull request merged**
